### ISSUE TITLE
服务器端主动关闭连接时，libpomelo未抛出事件

### ISSUE THREAD

**Issue by kilua626** [NetEase/libpomelo#40]
如题，应该在client.c的以下位置进行修改：
void pc__close_async_cb(uv_async_t *handle, int status) {
  pc_client_t *client = (pc_client_t *)handle->data;
  // 服务器端主动断开连接时，抛出断开事件
  pc_emit_event(client, PC_EVENT_DISCONNECT, NULL);
  pc_client_stop(client);
}

**Comment by cynron** [comment]
Closing, ^^
