### ISSUE TITLE
static inline是C99的标准，vs编译器编不过

### ISSUE THREAD

**Issue by rangercyh** [NetEase/libpomelo#72]
src\message.c 文件里

![1](https://cloud.githubusercontent.com/assets/1217541/5751737/35cfcb86-9ca3-11e4-8302-aebe688c3666.jpg)

上面3个用static inline修饰的函数无法在vs编译器通过，去掉对应的inline和下面定义地方的inline就可以编过了，建议去掉，保证windows平台用vs编译器可以编过。

**Comment by cynron** [comment]
到 #73 讨论吧，这个就关了
