### ISSUE TITLE
 ./build_ios failed 

### ISSUE THREAD

**Issue by zacharyhu** [NetEase/libpomelo#75]
/Users/zacharyhu/Downloads/libpomelo-master/src/pkg-handshake.c:211:3: error: 
      implicit declaration of function 'pc__heartbeat' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  pc__heartbeat(client);
  ^
/Users/zacharyhu/Downloads/libpomelo-master/src/pkg-handshake.c:127:32: warning: 
      implicit conversion loses integer precision: 'long long' to 'int'
      [-Wshorten-64-to-32]
        client->heartbeat = hb * 1000;
                          ~ ~~~^~~~~~
1 warning and 1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/pomelo.build/Default-iphoneos/libpomelo.build/Objects-normal/arm64/pkg-handshake.o src/pkg-handshake.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by cynron** [comment]
Fixed.
