### ISSUE TITLE
iOS切到后台，心跳超时后再返回应用，pc_client_stop调用uv_mutex_lock导致abort

### ISSUE THREAD

**Issue by linyehui** [NetEase/libpomelo#76]
iOS 应用使用libpomelo 版本0.3.2，
应用切到后台，开启飞行模式，等待心跳超时后再返回应用（不重现就等待久一点，5分钟以上），
这个时候会调用pc_client_stop，
而pc_client_stop会调用uv_mutex_lock，调用返回22，按照代码逻辑会直接调用abort。

void uv_mutex_lock(uv_mutex_t* mutex) {
  if (pthread_mutex_lock(mutex)) // 切到后台后回来，这里返回22
    abort();
}

**Comment by cynron** [comment]
libpomelo 以后不再维护,抱歉,请使用libpomelo2
