### ISSUE TITLE
Why this project is marked DEPRECATED while the libpomelo2 is still unstable.

### ISSUE THREAD

**Issue by xpol** [NetEase/libpomelo#77]
What's the difference between libpomelo2 and libpomelo?

**Comment by cynron** [comment]
libpomelo uses libuv in a wrong way,  most APIs of libuv are not thread-safe, excepting `uv_async_send` is thread-safe, but libpomelo breaks the rule,  and it leads to memory corruption, segment fault in our practice.

libpomelo2 is mostly stable, may lack of some validation check for argument or client status and docs. libpomelo2 works well in our production environment.

**Comment by xpol** [comment]
@cynron

Thank you!
Would please review https://github.com/NetEase/libpomelo2/pull/57.

**Comment by williamdu2877** [comment]
libpomelo2文档都没有，又不兼容旧的服务器端，比libpomelo也没好到哪里去。可用性甚至更差，初始编译都得折腾半天。
